nan:communication.py 146, __init__ > sibiu.py 17, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection SUCCESS
nan:logger.py 34, append_vehicle > sibiu.py 18, __init__ > main.py 16, __init__ > main.py 57, <module> : vehicle found, starting logging
1965628:sibiu.py 20, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection Success
1965638:sibiu.py 29, test > sibiu.py 45, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : performing test
1965638:communication.py 231, setmode > sibiu.py 30, test > sibiu.py 45, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : mode changed to MANUAL
1966633:communication.py 223, arm > sibiu.py 31, test > sibiu.py 45, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle arm
1976883:main.py 33, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : asked to close program
1977431:sibiu.py 65, raise_exception > sibiu.py 71, close > main.py 48, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : sibiu closed
1977536:communication.py 249, close > communication.py 240, safe_close > main.py 49, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : comm closed
1977731:main.py 51, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : close finished
1977833:main.py 41, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : joy read stopped
1977933:logger.py 75, save_data > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : log save thread closed
1979631:logger.py 86, sys_read > __init__.py 1531, notify_message_listeners > __init__.py 1053, listener > mavlink.py 240, mavlink_thread_in > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle was disarmed
1984931:communication.py 75, get_data > communication.py 89, get_acoustic_position > communication.py 99, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020B4CA46C40>: Failed to establish a new connection: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder'))
nan:communication.py 146, __init__ > sibiu.py 17, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection SUCCESS
nan:logger.py 34, append_vehicle > sibiu.py 18, __init__ > main.py 16, __init__ > main.py 57, <module> : vehicle found, starting logging
2003608:sibiu.py 20, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection Success
2003608:sibiu.py 29, test > sibiu.py 45, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : performing test
2004608:communication.py 231, setmode > sibiu.py 30, test > sibiu.py 45, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : mode changed to MANUAL
2004608:communication.py 223, arm > sibiu.py 31, test > sibiu.py 45, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle arm
2006603:logger.py 86, sys_read > __init__.py 1531, notify_message_listeners > __init__.py 1053, listener > mavlink.py 240, mavlink_thread_in > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle was armed
2008563:main.py 33, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : asked to close program
2008965:sibiu.py 65, raise_exception > sibiu.py 71, close > main.py 48, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : sibiu closed
2008965:communication.py 249, close > communication.py 240, safe_close > main.py 49, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : comm closed
2009366:main.py 51, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : close finished
2009366:logger.py 75, save_data > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : log save thread closed
2009366:main.py 33, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : asked to close program
2009366:sibiu.py 65, raise_exception > sibiu.py 71, close > main.py 48, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : sibiu closed
2009366:communication.py 249, close > communication.py 240, safe_close > main.py 49, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : comm closed
2009366:main.py 51, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : close finished
2009366:main.py 33, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : asked to close program
2009366:sibiu.py 65, raise_exception > sibiu.py 71, close > main.py 48, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : sibiu closed
2009366:communication.py 249, close > communication.py 240, safe_close > main.py 49, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : comm closed
2009366:main.py 51, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : close finished
2009366:main.py 41, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : joy read stopped
2022061:communication.py 75, get_data > communication.py 89, get_acoustic_position > communication.py 99, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5C10D2190>: Failed to establish a new connection: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder'))
2032961:communication.py 75, get_data > communication.py 92, get_global_position > communication.py 100, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D5C26C6280>: Failed to establish a new connection: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder'))
2032963:communication.py 114, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : gps log closed
