nan:communication.py 103, __init__ > sibiu.py 17, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection SUCCESS
nan:logger.py 34, append_vehicle > sibiu.py 18, __init__ > main.py 16, __init__ > main.py 57, <module> : vehicle found, starting logging
502714:sibiu.py 20, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection Success
502714:sibiu.py 29, test > sibiu.py 44, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : performing test
502714:communication.py 177, setmode > sibiu.py 30, test > sibiu.py 44, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : mode changed to GUIDED
503714:communication.py 169, arm > sibiu.py 31, test > sibiu.py 44, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle arm
504711:logger.py 86, sys_read > __init__.py 1531, notify_message_listeners > __init__.py 1053, listener > mavlink.py 240, mavlink_thread_in > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle was armed
510847:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF45D520>: Failed to establish a new connection: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host'))
510847:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68F130>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
510851:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF41AA00>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
510947:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF45D3A0>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511047:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68F340>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511047:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF689700>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511051:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68FDF0>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511147:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6A00D0>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511247:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6A0640>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511349:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6B0070>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511547:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6B0760>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511547:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF41AA60>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511647:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF41AFA0>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511649:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D65E0>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
511747:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF41ABE0>: Failed to establish a new connection: [WinError 10051] Se ha intentado una operación de socket en una red no accesible'))
553179:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured ('Connection aborted.', ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None))
561681:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E0490>: Failed to establish a new connection: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host'))
561879:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6DF280>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
561981:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6F89D0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
562179:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E5610>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
562477:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D7DF0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
562979:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FF3A0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
563477:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D7340>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
564079:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E5430>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
564579:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2D00>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
564777:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF7002E0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
565279:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF700FD0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
565379:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FFA90>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
566101:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6DF280>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
566407:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2C40>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
567704:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6DC310>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
572701:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6DCA60>: Failed to establish a new connection: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host'))
573304:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E9700>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
574001:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E4A60>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
574701:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2430>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
575404:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2820>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
575801:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E5970>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
576404:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E25E0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
577301:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D76A0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
578201:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6F77F0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
579001:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D7220>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
579801:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D72B0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
580307:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6DC490>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
581201:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E5F40>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
581301:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6DC850>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
581401:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6F7E20>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
581501:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF700190>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
581601:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6F34F0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
581701:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FF8E0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
581901:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6DC250>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
582001:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF71A9A0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
582101:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2AF0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
582501:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6894F0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
584101:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF689F10>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
585901:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EAFD0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
587801:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EA430>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
588101:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF694E20>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
588601:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D8F70>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
588701:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF7003D0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
589001:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF689A30>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
589501:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF689DC0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
589707:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68F280>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
589901:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EA9D0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
590001:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D84F0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
590201:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D80A0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
590701:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FB400>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
591401:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6B0BE0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
591901:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF700370>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
592007:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EA4C0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
592901:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D8190>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
593901:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EA970>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
594101:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF700550>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
594501:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EA910>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
595807:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FBEB0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
596601:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68F700>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
597401:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D8A60>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
597501:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FB640>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
598001:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6B03D0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
598601:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68F640>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
600001:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2A60>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
600601:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EA130>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
601001:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FFCD0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
601101:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D8790>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
601601:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D83A0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
602101:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EAC70>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
602304:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EA370>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
603004:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FB2E0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
604137:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FBFA0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
604879:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FB7F0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
605639:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FFBE0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
605881:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2460>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
606639:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6EAD00>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
607137:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68FF40>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
607379:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E82E0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
607639:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FB4C0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
607879:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6FBDF0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
607889:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF68F7F0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
608379:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E2460>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
608381:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6E8DF0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
608639:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022DDF6D8AC0>: Failed to establish a new connection: [WinError 10065] Se ha intentado una operación de socket en un host no accesible'))
608879:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
609139:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
609379:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
609381:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
609389:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
609879:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
609879:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
609882:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
635421:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
635821:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
636021:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
636121:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
636321:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
636721:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
640921:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
644899:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
646399:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
647161:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
647901:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
649399:communication.py 39, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
649901:communication.py 39, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Got error 500: 
697749:logger.py 88, sys_read > __init__.py 1531, notify_message_listeners > __init__.py 1053, listener > mavlink.py 240, mavlink_thread_in > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : mode changed to GUIDED
725427:main.py 33, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : asked to close program
725924:sibiu.py 64, raise_exception > sibiu.py 69, close > main.py 48, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : sibiu closed
725927:communication.py 195, close > communication.py 186, safe_close > main.py 49, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : comm closed
726179:main.py 51, close > main.py 34, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : close finished
726424:main.py 41, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : joy read stopped
726424:logger.py 75, save_data > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : log save thread closed
727424:communication.py 71, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : gps log closed
