nan:communication.py 148, __init__ > sibiu.py 17, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection SUCCESS
nan:logger.py 34, append_vehicle > sibiu.py 18, __init__ > main.py 16, __init__ > main.py 57, <module> : vehicle found, starting logging
371.502534:sibiu.py 20, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection Success
371.502534:sibiu.py 29, test > sibiu.py 46, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : performing test
373.42022:communication.py 242, setmode > sibiu.py 30, test > sibiu.py 46, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : mode changed to MANUAL
373.42022:communication.py 234, arm > sibiu.py 32, test > sibiu.py 46, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle arm
391.84384:communication.py 75, get_data > communication.py 89, get_acoustic_position > communication.py 99, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPConnectionPool(host='192.168.7.1', port=80): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000210F13C3CA0>: Failed to establish a new connection: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder'))
392.071472:main.py 64, <module> : asked to finish program
392.071472:sibiu.py 66, raise_exception > sibiu.py 73, close > main.py 48, close > main.py 65, <module> : sibiu closed
392.071472:main.py 41, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : joy read stopped
392.071472:communication.py 260, close > communication.py 251, safe_close > main.py 49, close > main.py 65, <module> : comm closed
392.071472:main.py 51, close > main.py 65, <module> : close finished
392.071472:logger.py 89, save_data > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : log save thread closed
nan:communication.py 148, __init__ > sibiu.py 17, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection SUCCESS
nan:logger.py 34, append_vehicle > sibiu.py 18, __init__ > main.py 16, __init__ > main.py 57, <module> : vehicle found, starting logging
405.791169:sibiu.py 20, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection Success
406.172265:sibiu.py 29, test > sibiu.py 46, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : performing test
406.172265:communication.py 242, setmode > sibiu.py 30, test > sibiu.py 46, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : mode changed to MANUAL
408.039087:communication.py 234, arm > sibiu.py 32, test > sibiu.py 46, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : vehicle arm
418.870233:main.py 64, <module> : asked to finish program
419.622243:main.py 41, check_joy_interrupt > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : joy read stopped
419.622243:sibiu.py 66, raise_exception > sibiu.py 73, close > main.py 48, close > main.py 65, <module> : sibiu closed
419.622243:communication.py 260, close > communication.py 251, safe_close > main.py 49, close > main.py 65, <module> : comm closed
419.622243:main.py 51, close > main.py 65, <module> : close finished
419.622243:logger.py 89, save_data > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : log save thread closed
