nan:communication.py 103, __init__ > sibiu.py 17, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection SUCCESS
nan:logger.py 34, append_vehicle > sibiu.py 18, __init__ > main.py 16, __init__ > main.py 57, <module> : vehicle found, starting logging
4445619:sibiu.py 20, __init__ > main.py 16, __init__ > main.py 57, <module> : Connection Success
4446624:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002774FF447F0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4449624:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000277511F4280>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4452624:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002775123E730>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4454452:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027751276F10>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4455254:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002775126D8B0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4456052:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027750107E80>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4456757:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000277501004C0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4457356:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000277501181C0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4457952:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002775012E040>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4458354:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027750118EE0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4458652:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027751276820>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4458857:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002775128D7C0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4459152:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002775128DFD0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4460654:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000277500F67F0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4461352:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027751288A60>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4462252:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027751289B80>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4463954:communication.py 35, get_data > communication.py 49, get_acoustic_position > communication.py 59, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/acoustic/filtered (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002775125DF10>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
4464952:communication.py 35, get_data > communication.py 52, get_global_position > communication.py 60, read_gps_thread > threading.py 917, run > threading.py 980, _bootstrap_inner > threading.py 937, _bootstrap : Exception occured HTTPSConnectionPool(host='192.168.7.1', port=443): Max retries exceeded with url: /api/v1/position/global (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027751289E20>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
